### ISSUE TITLE
默认记分板配置

### ISSUE THREAD

**Issue by Rhacoal** [leonardodalinky/ThuBP-backend#13]
目前的记分板配置需要将各自的 Config 存入各自的 Game，有考虑将这一部分提取到 Match 或 Round 层面，因为这个配置是几乎不会变动的。

Game 目前的记分
 - scoreboardTypeId
 - scoreboardConfig (Object implements GameScoreboardConfig, 挺大的)
 - result (Object extends GameResult, 虽然挺大但也没办法)

如果能将 scoreboardConfig 复用可能会很方便，不过目前来看还没有编辑这一 Config 的需求。如果出于节约存储的考虑可以尝试一下，但优先度不高？

**Comment by leonardodalinky** [comment]
已经改为 extra 字段了？
